#include <filesystem>

#include <Sparsix/MatrixCOO.h>
#include <Sparsix/Concepts/SparseMatrix.h>
#include <Sparsix/IO/Detail.h>

namespace sparsix {
    template <SparseMatrix Matrix>
    void write_matrix_market(const Matrix &matrix, const std::filesystem::path &path) {
        using T = typename Matrix::value_type;
        std::ofstream output(path);
        if (!output)
            throw std::runtime_error("Unable to open Matrix Market file for writing: " + path.string());

        const auto &coo = toCOO(matrix);
        output << "%%MatrixMarket matrix coordinate " << (is_std_complex_v<T> ? "complex" : "real") << " general\n";
        output << "% Generated by Sparsix\n";
        output << coo.rows_count() << ' ' << coo.cols_count() << ' ' << coo.non_zero_count() << '\n';
        output << std::setprecision(std::numeric_limits<long double>::max_digits10);
        for (size_t i = 0; i < coo.non_zero_count(); i++) {
            output << coo.rows()[i] + 1 << ' ' << coo.cols()[i] + 1 << ' ';
            io_detail::write_value(output, coo.values()[i]);
            output << '\n';
        }
    }

    template <SparseMatrix Matrix>
    Matrix read_matrix_market(const std::filesystem::path &path) {
        using T = typename Matrix::value_type;
        std::ifstream input(path);
        if (!input)
            throw std::runtime_error("Unable to open Matrix Market file for reading: " + path.string());

        std::string header;
        std::getline(input, header);
        std::istringstream header_stream(io_detail::lowercase(header));
        std::string magic, object, format, field, symmetry;
        header_stream >> magic >> object >> format >> field >> symmetry;
        if (magic != "%%matrixmarket" || object != "matrix" || format != "coordinate")
            throw std::invalid_argument("Only Matrix Market coordinate matrices are supported.");
        if (field != "real" && field != "integer" && field != "complex" && field != "pattern")
            throw std::invalid_argument("Unsupported Matrix Market value field.");
        if (symmetry != "general" && symmetry != "symmetric" && symmetry != "skew-symmetric" && symmetry != "hermitian")
            throw std::invalid_argument("Unsupported Matrix Market symmetry.");
        if (field == "complex" && !is_std_complex_v<T>)
            throw std::invalid_argument("Cannot read complex values into a real matrix type.");
        if (symmetry == "hermitian" && !is_std_complex_v<T>)
            throw std::invalid_argument("Hermitian Matrix Market matrices require a complex matrix type.");

        const auto dimensions_line = io_detail::next_data_line(input, '%');
        std::istringstream dimensions(dimensions_line);
        size_t rows{}, cols{}, nnz{};
        if (!(dimensions >> rows >> cols >> nnz))
            throw std::invalid_argument("Invalid Matrix Market dimensions line.");
        if ((symmetry != "general") && rows != cols)
            throw std::invalid_argument("Symmetric Matrix Market matrices must be square.");

        std::vector<Triplet<T>> triplets;
        triplets.reserve(nnz * (symmetry == "general" ? 1 : 2));
        for (size_t i = 0; i < nnz; i++) {
            const auto line = io_detail::next_data_line(input, '%');
            std::istringstream entry(line);
            size_t row{}, col{};
            if (!(entry >> row >> col) || row == 0 || col == 0 || row > rows || col > cols)
                throw std::invalid_argument("Invalid Matrix Market coordinate.");

            T value = field == "pattern" ? T{1} : io_detail::read_value<T>(entry, field == "complex");
            if (!entry)
                throw std::invalid_argument("Invalid Matrix Market value.");
            row--;
            col--;
            triplets.push_back({row, col, value});

            if (row != col && symmetry != "general") {
                T mirrored = value;
                if (symmetry == "skew-symmetric")
                    mirrored = -value;
                else if (symmetry == "hermitian") {
                    if constexpr (is_std_complex_v<T>)
                        mirrored = std::conj(value);
                }
                triplets.push_back({col, row, mirrored});
            }
        }

        return io_detail::build_matrix<Matrix>(rows, cols, std::move(triplets));
    }

    template <typename T>
    MatrixCOO<T> load_matrix_market(const std::filesystem::path &path) {
        return read_matrix_market<MatrixCOO<T>>(path);
    }

    template <SparseMatrix Matrix>
    void save_matrix_market(const Matrix &matrix, const std::filesystem::path &path) {
        write_matrix_market(matrix, path);
    }
}
