#pragma once

#include <filesystem>
#include <fstream>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <Sparsix/MatrixCOO.h>
#include <Sparsix/Concepts/SparseMatrix.h>
#include <Sparsix/IO/Detail.h>

namespace sparsix {

/**
 * @brief Writes a sparse matrix in Matrix Market coordinate format.
 * @tparam Matrix Any supported sparse matrix type.
 * @param matrix Matrix to serialize.
 * @param path Destination `.mtx` file.
 * @throws std::runtime_error If the destination cannot be opened.
 *
 * Complex values are written as real/imaginary pairs and all coordinates are
 * converted to Matrix Market's one-based indexing.
 */
template <SparseMatrix Matrix>
void write_matrix_market(const Matrix &matrix, const std::filesystem::path &path) {
    using T = typename Matrix::value_type;
    std::ofstream output(path);
    if (!output)
        throw std::runtime_error("Unable to open Matrix Market file for writing: " + path.string());
        
    const auto &coo = toCOO(matrix);
    output << "%%MatrixMarket matrix coordinate " << (is_std_complex_v<T> ? "complex" : "real") << " general\n";
    output << "% Generated by Sparsix\n";
    output << coo.rows_count() << ' ' << coo.cols_count() << ' ' << coo.non_zero_count() << '\n';
    output << std::setprecision(std::numeric_limits<long double>::max_digits10);
    for (size_t i = 0; i < coo.non_zero_count(); ++i) {
        output << coo.rows()[i] + 1 << ' ' << coo.cols()[i] + 1 << ' ';
        detail::io::write_value(output, coo.values()[i]);
        output << '\n';
    }
}

/**
 * @brief Reads a Matrix Market coordinate matrix into a selected storage format.
 * @tparam Matrix Target sparse matrix type, for example `MatrixCSR<double>`.
 * @param path Source `.mtx` file.
 * @return Parsed matrix in the requested format.
 * @throws std::invalid_argument For unsupported or malformed content.
 * @throws std::runtime_error If the source cannot be opened.
 *
 * The reader supports real, integer, complex and pattern fields and general,
 * symmetric, skew-symmetric and Hermitian symmetry modes.
 */
template <SparseMatrix Matrix>
Matrix read_matrix_market(const std::filesystem::path &path) {
    using T = typename Matrix::value_type;
    std::ifstream input(path);

    if (!input)
        throw std::runtime_error("Unable to open Matrix Market file for reading: " + path.string());

    std::string header;
    std::getline(input, header);
    std::istringstream header_stream(detail::io::lowercase(header));
    std::string magic, object, format, field, symmetry;
    header_stream >> magic >> object >> format >> field >> symmetry;
    if (magic != "%%matrixmarket" || object != "matrix" || format != "coordinate")
        throw std::invalid_argument("Only Matrix Market coordinate matrices are supported.");
    if (field != "real" && field != "integer" && field != "complex" && field != "pattern")
        throw std::invalid_argument("Unsupported Matrix Market value field.");
    if (symmetry != "general" && symmetry != "symmetric" && symmetry != "skew-symmetric" && symmetry != "hermitian")
        throw std::invalid_argument("Unsupported Matrix Market symmetry.");
    if (field == "complex" && !is_std_complex_v<T>)
        throw std::invalid_argument("Cannot read complex values into a real matrix type.");
    if (symmetry == "hermitian" && !is_std_complex_v<T>)
        throw std::invalid_argument("Hermitian Matrix Market matrices require a complex matrix type.");

    const auto dimensions_line = detail::io::next_data_line(input, '%');
    std::istringstream dimensions(dimensions_line);
    size_t rows{}, cols{}, nnz{};
    if (!(dimensions >> rows >> cols >> nnz))
        throw std::invalid_argument("Invalid Matrix Market dimensions line.");
    if ((symmetry != "general") && rows != cols)
        throw std::invalid_argument("Symmetric Matrix Market matrices must be square.");

    std::vector<Triplet<T>> triplets;
    triplets.reserve(nnz * (symmetry == "general" ? 1 : 2));
    for (size_t i = 0; i < nnz; ++i) {
        const auto line = detail::io::next_data_line(input, '%');
        std::istringstream entry(line);
        size_t row{}, col{};
        if (!(entry >> row >> col) || row == 0 || col == 0 || row > rows || col > cols)
            throw std::invalid_argument("Invalid Matrix Market coordinate.");
        
        T value = field == "pattern" ? T{1} : detail::io::read_value<T>(entry, field == "complex");
        if (!entry)
            throw std::invalid_argument("Invalid Matrix Market value.");

        row--;
        col--;
        triplets.push_back({row, col, value});
        if (row != col && symmetry != "general") {
            T mirrored = value;
            if (symmetry == "skew-symmetric")
                mirrored = -value;
            else if (symmetry == "hermitian") {
                if constexpr (is_std_complex_v<T>)
                    mirrored = std::conj(value);
            }
            triplets.push_back({col, row, mirrored});
        }
    }

    return detail::io::build_matrix<Matrix>(rows, cols, std::move(triplets));
}

/** @brief Reads a Matrix Market file into COO storage. */
template <typename T>
MatrixCOO<T> load_matrix_market(const std::filesystem::path &path) {
    return read_matrix_market<MatrixCOO<T>>(path);
}

/** @brief Writes a matrix in Matrix Market format; alias for write_matrix_market(). */
template <SparseMatrix Matrix>
void save_matrix_market(const Matrix &matrix, const std::filesystem::path &path) {
    write_matrix_market(matrix, path);
}

} // namespace sparsix
